version: "3.5"

services:
  openmpi:
    image: mfisherman/openmpi
    command: >
      tail -f /dev/null
    volumes:
      - ./project:/project
  openmpi_ff:
    image: mfisherman/openmpi
    command: >
      sh -c "cd /project && mpicc program.c && ./a.out 4 | xargs echo && tail -f /dev/null"
    volumes:
      - ./project:/project
  openmp:
    image: mfisherman/openmp
    command: >
      tail -f /dev/null
    volumes:
      - ./project:/project